memory_limit=1024M
upload_max_filesize=256M
post_max_size=256M
max_execution_time=1200
max_input_time=1200
default_socket_timeout=1200
date.timezone=Europe/Vienna

opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0
opcache.save_comments=1
